- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
